# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exclusive_lasso_project <- function(x, lambda) {
    .Call('_BCEL_exclusive_lasso_project', PACKAGE = 'BCEL', x, lambda)
}

exclusive_lasso <- function(y, x, group, lambda, iter_max, tol) {
    .Call('_BCEL_exclusive_lasso', PACKAGE = 'BCEL', y, x, group, lambda, iter_max, tol)
}

BiElasso <- function(X, r, lambda_u, lambda_v, iter_max, tol) {
    .Call('_BCEL_BiElasso', PACKAGE = 'BCEL', X, r, lambda_u, lambda_v, iter_max, tol)
}

BiElasso_bootstrap <- function(X, Omega, r, lambda_u, lambda_v, iter_max, tol) {
    .Call('_BCEL_BiElasso_bootstrap', PACKAGE = 'BCEL', X, Omega, r, lambda_u, lambda_v, iter_max, tol)
}

good_sample <- function(x, n, p, sample_size, r) {
    .Call('_BCEL_good_sample', PACKAGE = 'BCEL', x, n, p, sample_size, r)
}

BiElasso_stable <- function(X, r, q_u = 0.2, q_v = 0.2, q_upper = 0.5, select_upper_u = 0.45, select_upper_v = 0.45, B1 = 10, B2 = 200, pi_thr_l = 0.65, pi_thr_u = 0.7, size_per = 0.5, speed = 0.3, iter_max = 100L, tol = 0.000001, sparse = 0L) {
    .Call('_BCEL_BiElasso_stable', PACKAGE = 'BCEL', X, r, q_u, q_v, q_upper, select_upper_u, select_upper_v, B1, B2, pi_thr_l, pi_thr_u, size_per, speed, iter_max, tol, sparse)
}

BiElasso_cv <- function(X, r_list, q_u = 0.2, q_v = 0.2, q_upper = 0.5, select_upper_u = 0.45, select_upper_v = 0.45, B1 = 10, B2 = 200, cv_k = 5L, pi_thr_l = 0.65, pi_thr_u = 0.7, size_per = 0.5, speed = 0.3, iter_max = 100L, tol = 0.000001, sparse = 0L) {
    .Call('_BCEL_BiElasso_cv', PACKAGE = 'BCEL', X, r_list, q_u, q_v, q_upper, select_upper_u, select_upper_v, B1, B2, cv_k, pi_thr_l, pi_thr_u, size_per, speed, iter_max, tol, sparse)
}

BiElasso_chooser <- function(X, r_list, q_u = 0.2, q_v = 0.2, q_upper = 0.5, select_upper_u = 0.45, select_upper_v = 0.45, B1 = 10, B2 = 200, pi_thr_l = 0.65, pi_thr_u = 0.7, size_per = 0.5, speed = 0.3, iter_max = 100L, tol = 0.000001, sparse = 0L) {
    .Call('_BCEL_BiElasso_chooser', PACKAGE = 'BCEL', X, r_list, q_u, q_v, q_upper, select_upper_u, select_upper_v, B1, B2, pi_thr_l, pi_thr_u, size_per, speed, iter_max, tol, sparse)
}

